#!/bin/bash 

wget https://lofar-surveys.org/public/mosaics/P10Hetdex-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P11Hetdex12-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P12Hetdex11-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P14Hetdex04-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P15Hetdex13-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P164+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P169+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P16Hetdex13-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P173+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P178+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P182+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P187+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P18Hetdex03-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P191+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P196+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P19Hetdex17-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P1Hetdex15-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P200+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P205+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P206+50-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P206+52-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P209+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P21-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P210+47-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P211+50-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P213+47-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P214+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P217+47-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P218+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P219+50-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P219+52-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P221+47-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P223+50-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P223+52-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P223+55-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P225+47-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P227+50-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P227+53-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P22Hetdex04-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P23Hetdex20-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P25Hetdex09-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P26Hetdex03-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P27Hetdex09-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P29Hetdex19-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P30Hetdex06-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P33Hetdex08-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P34Hetdex06-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P35Hetdex10-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P37Hetdex15-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P38Hetdex07-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P39Hetdex19-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P3Hetdex16-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P41Hetdex-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P42Hetdex07-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P4Hetdex16-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P6-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P7Hetdex11-mosaic.fits --no-check-certificate
wget https://lofar-surveys.org/public/mosaics/P8Hetdex-mosaic.fits --no-check-certificate
